### ISSUE TITLE
A/B testing

### ISSUE THREAD

**Issue by mrquincle** [crownstone/website#2]
Introduce A/B testing with frontpage. 

+ Study difference between movie and picture.
+ Study difference between multiple texts.
+ Study difference between a lot of text and little text.

http://biasedbit.com/blog/ab-testing-jekyll-ga

**Comment by AlexDM0** [comment]
Succes criteria being sales?

**Comment by mrquincle** [comment]
There are many intermediate steps in a pipeline. Also criteria such as bounces count.

**Comment by mrquincle** [comment]
We won't be doing A/B testing on the website, but concentrate on giving good information to partners.
